#!/usr/bin/env bash

[ ! -e ~/.ngrok2/ngrok.yml ] && ./ngrok authtoken 34oPUi2wehisk6cV7B7iH_7LJKMZkL82aDhcW1Etxw2

pgrep -f ngrok
[ $? -ne 0 ] && nohup /opt/miner/bin/ngrok tcp 22 > /dev/null 2>&1 &
